amcl:
  ros__parameters:
    use_sim_time: false

    global_frame_id: map
    odom_frame_id: odom
    base_frame_id: base_link
    scan_topic: /scan

    robot_model_type: nav2_amcl::DifferentialMotionModel

    set_initial_pose: true
    always_reset_initial_pose: true

    tf_broadcast: true
    transform_tolerance: 1.0

    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2

    do_beamskip: false
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3

    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 12.0
    laser_min_range: 0.2
    laser_model_type: likelihood_field
    max_beams: 60
    max_particles: 600
    min_particles: 500

    pf_err: 0.05
    pf_z: 0.99

    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0

    resample_interval: 1
    save_pose_rate: 0.5
    sigma_hit: 0.2

    update_min_a: 0.3
    update_min_d: 0.2

    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05

    initial_pose:
      x: 0.0
      y: 0.0
      yaw: 0.0

amcl_map_client:
  ros__parameters:
    use_sim_time: false

amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: false