/**:
  ros__parameters:
    use_color: false
    use_lidar: false
    input_qos: "SENSOR_DATA"
    map_clearing_radius_m: 2.0

    static_mapper:
      esdf_slice_height: 0.06
      esdf_slice_min_height: 0.05
      esdf_slice_max_height: 0.5
