# --- Parametry identyfikacyjne ---
camera_name: "camera"
device_type: ''
serial_no: ''
usb_port_id: ''
initial_reset: true
publish_tf: true        # <--- WAŻNE: Musi być true!

# --- Ustawienia RGB ---
enable_color: true
rgb_camera:
  profile: "640x360x30"
color_info_qos: "SENSOR_DATA"
color_qos: "SENSOR_DATA"

# --- Ustawienia Depth ---
enable_depth: true
depth_module:
  profile: "640x360x30"
  emitter_enabled: 1
  emitter_on_off: true    # Stały laser jest lepszy, ale zostawiam jak chcesz
  enable_auto_exposure: true
depth_qos: "SENSOR_DATA"
depth_info_qos: "SENSOR_DATA"

# --- Ustawienia Infra (VSLAM) ---
enable_infra1: true
enable_infra2: true
infra_qos: "SENSOR_DATA"

# --- IMU i Sync (VSLAM + Segformer) ---
enable_sync: true
enable_gyro: true
enable_accel: true
unite_imu_method: 2
gyro_fps: 200
accel_fps: 250

# --- NVBLOX / Segformer ---
align_depth: true       # Zmieniono składnię na prostszą (dla płaskiego YAML)
pointcloud:
  enable: false