ekf_filter_node:
  ros__parameters:
    frequency: 60.0               # Jak często działa filtr (Hz)
    sensor_timeout: 0.3           # Jak długo czeka na dane z sensora (sekundy)

    two_d_mode: true              # Praca 2D – wyłącza Z i roll/pitch
    publish_tf: true              # Publikuje transformację odom → base_link
    publish_acceleration: false

    map_frame: map                # Używane tylko gdy jest drugi EKF (globalny)
    odom_frame: odom              # Ramka lokalna (bazowa)
    base_link_frame: base_link    # Ramka robota
    world_frame: odom             # Dla tego EKF odom = world

    use_control: false            # Nie używasz danych z np. /cmd_vel

    odom0: diff_cont/odom
    odom0_config: [true,  true,  true,   # x, y, z
                   false, false, false,   # roll, pitch, yaw
                   false, false, false,     # vx, vy, vz
                   false, false, false,    # vroll, vpitch, vyaw
                   false, false, false]   # ax, ay, az

    imu0: camera/imu
    imu0_config: [false, false, false,   # x, y, z
                  false, false, false,    # roll, pitch, yaw (tylko yaw)
                  false, false, false,   # vx, vy, vz
                  false, false, true,    # vroll, vpitch, vyaw (tylko wyaw)
                  false, false, false]   # ax, ay, az

    odom0_differential: false
    odom0_relative: false

    imu0_differential: false
    imu0_relative: true

    imu0_remove_gravitational_acceleration: true

    print_diagnostics: true       # Przydatne przy debugowaniu
