controller_manager:
  ros__parameters:
    update_rate: 60
    diff_cont:
      type: diff_drive_controller/DiffDriveController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    use_stamped_vel: false
    publish_rate: 60.0
    publish_limited_velocity: true
    base_frame_id: base_link
    odom_frame_id: odom
    publish_odometry_tf: false
    enable_odom_tf: false
    left_wheel_names: ["left_wheel_1_joint", "left_wheel_2_joint", "left_wheel_3_joint"]
    right_wheel_names: ["right_wheel_1_joint", "right_wheel_2_joint", "right_wheel_3_joint"]
    wheel_separation: 0.55  # 6_wheel_robot.urdf.xacro 0.657    robot_luksusowy.urdf.xacro 0.55
    wheel_radius: 0.085     # 6_wheel_robot.urdf.xacro 0.1016   robot_luksusowy.urdf.xacro 0.085
    wheels_per_side: 3
    odom_middle_wheel_calc: false
    # pose_covariance_diagonal: [
    #   0.1, 0.1, 0.1,    # x, y, z 
    #   0.1, 0.1, 0.1,    # roll, pitch, yaw 
    #   ]
    # twist_covariance_diagonal: [
    #   0.1, 0.1, 0.1,    # vx, vy, vz 
    #   0.1, 0.1, 0.1,    # vroll, vpitch, vyaw
    #   ]
    

